librarys1/books/urls.py
from django.contrib import admin
from django.urls import path

from books import views

app_name="books"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home,name="home"),
    path("view",views.view,name="view"),
    path("add",views.add,name="add"),
    path("detail/<int:p>",views.detail,name="detail"),
    path("delete/<int:p>", views.delete, name="delete"),
    path("edit/<int:p>", views.edit, name="edit"),

]

librarys1/librarys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('users/',include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

librarys1/users/urls.py
from django.contrib import admin
from django.urls import path

from users import views

app_name="users"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("userregister",views.userregister,name="userregister"),
    path("adminregister", views.adminregister, name="adminregister"),
    path("user_login",views.user_login,name="login"),
    path("user_logout",views.user_logout,name="logout"),
]

librarys1/books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    price = models.IntegerField()
    pages = models.IntegerField()
    language = models.CharField(max_length=20)
    cover=models.ImageField(upload_to="cover")
    pdf=models.FileField(upload_to="pdf")


    def __str__(self):
        return self.title

librarys1/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Users(models.Model):
    name = models.CharField(max_length=20)
    place = models.CharField(max_length=20)
    age = models.IntegerField()
    gender = models.CharField(max_length=20)


    def __str__(self):
        return self.name


class CustomUser(AbstractUser):
    phone=models.BigIntegerField(default=0)
    address=models.CharField(max_length=20,default="")
    is_superuser = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)

librarys1/books/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

# Create your views here.


def home(request):
    return render(request,'home.html')


from books.models import Book



@login_required
def view(request):
    k=Book.objects.all()                                      #reads all records from the book table
    context={'book':k}                                        #sends data from view function to html page
    return render(request,'view.html',context)


@login_required
def add(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        pa=request.POST['pa']
        l=request.POST['l']
        i=request.FILES.get('i')
        f=request.FILES.get('f')

        b=Book.objects.create(title=t,author=a,price=p,pages=pa,language=l,cover=i,pdf=f)
        b.save()
        return view(request)

    return render(request,'add.html')

@login_required
def detail(request,p):
    k=Book.objects.get(id=p)     # read the particular record
    context={'book':k}
    return render(request,'detail.html',context)

@login_required
def delete(request,p):
    k = Book.objects.get(id=p)
    k.delete()
    return redirect('books:view')


@login_required
def edit(request,p):
    k = Book.objects.get(id=p)
    if(request.method=="POST"):
        k.title=request.POST['t']
        k.author=request.POST['a']
        k.price=request.POST['p']
        k.pages=request.POST['pa']
        k.language=request.POST['l']

        if(request.FILES.get('i')==None):
            k.save()

        else:
            k.cover=request.FILES.get('i')

        if (request.FILES.get('f') == None):
            k.save()

        else:
            k.pdf = request.FILES.get('f')

        k.save()

        return redirect('books:view')

    context={'book':k}

    return render(request,'edit.html',context)

librarys1/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth import login,authenticate,logout
from users.models import CustomUser
# Create your views here.


def userregister(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        ph=request.POST['ph']
        a=request.POST['a']


        if(p==cp):
            u=CustomUser.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l,phone=ph,address=a,is_user=True)
            u.save()
            return redirect('books:home')

        else:
            return HttpResponse("password are not same")

    return render(request,'userregister.html')



def adminregister(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        ph=request.POST['ph']
        a=request.POST['a']


        if(p==cp):
            u=CustomUser.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l,phone=ph,address=a,is_superuser=True)
            u.save()
            return redirect('books:home')

        else:
            return HttpResponse("password are not same")

    return render(request,'adminregister.html')



def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)

        if user and user.is_superuser==True:
            login(request,user)
            return redirect('books:home')

        elif user and user.is_user==True:
            login(request,user)
            return redirect('books:home')

        else:
            return HttpResponse("invalid credentials")
    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('users:login')

librarys1/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3"><b>Add Book Details</b></h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3">
  <label  class="form-label">Title</label>
  <input type="text" class="form-control" name="t"  placeholder="Title of the Book">
</div>

        <div class="mb-3">
  <label  class="form-label">Author</label>
  <input type="text" class="form-control" name="a" placeholder="Author name">
</div>

            <div class="mb-3">
  <label  class="form-label">Price</label>
  <input type="text" class="form-control" name="p"  placeholder="price of th Book">
</div>

<div class="mb-3">
  <label  class="form-label">pages</label>
  <input type="text" class="form-control" name="pa" placeholder="number of pages">
</div>


<div class="mb-3">
  <label  class="form-label">language</label>
  <input type="text" class="form-control" name="l"  placeholder="language of the Book">
</div>


<div class="mb-3">
  <label  class="form-label">Cover</label>
  <input type="file" class="form-control" name="i">
</div>



<div class="mb-3">
  <label  class="form-label">Pdf</label>
  <input type="file" class="form-control" name="f">
</div>


    <div class="mb-3">
        <input type="submit" value="ADD">
    </div>




</form>
{% endblock %}

librarys1/templates/adminregister.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3"><b>Admin Register Form</b></h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

<div class="mb-3">
  <label  class="form-label">User name</label>
  <input type="text" class="form-control" name="u"  placeholder="enter user name">
</div>


<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>


<div class="mb-3">
  <label  class="form-label">confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter confirm password">
</div>


<div class="mb-3">
  <label  class="form-label">First Name</label>
  <input type="text" class="form-control" name="f"  placeholder="enter first name">
</div>


<div class="mb-3">
  <label  class="form-label">Last Name</label>
  <input type="text" class="form-control" name="l" placeholder="enter last name">
</div>


<div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="email" class="form-control" name="e"  placeholder="enter email">
</div>


<div class="mb-3">
  <label  class="form-label">Phone</label>
  <input type="number" class="form-control" name="ph"  placeholder="enter phone number">
</div>


<div class="mb-3">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control" name="a"  placeholder="enter address">
</div>



<div class="mb-3">
    <input type="submit" class="form-control btn btn-primary">
</div>




</form>



{% endblock %}

librarys1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>



<nav class="navbar navbar-expand-lg navbar-info bg-warning  ">
  <div class="container">
    <a class="navbar-brand fs-3" href="#">My Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home page</a>
        </li>

          {% if user.is_authenticated %}
        {% if user.is_superuser == True %}

                         <li class="nav-item">
          <a class="nav-link" href="{% url 'books:add' %}">Add Book</a>
        </li>
        {% endif %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:view' %}">view page</a>
        </li>


                              <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">logout</a>
        </li>

          {% else %}
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Register
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'users:userregister' %}">User</a></li>
            <li><a class="dropdown-item" href="{% url 'users:adminregister' %}">Admin</a></li>

          </ul>
        </li>


          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">login</a>
        </li>
          {% endif %}



      </ul>
    </div>
  </div>
</nav>

{% block content %}
hello
{% endblock %}
</body>
</html>

librarys1/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3"><b>Book Details</b></h2>
<div class="card mb-3 mt-5 mx-auto p-4 bg-info text-light" style="max-width:650px;">
  <div class="row g-0">
    <div class="col-md-4 p-2">
      <img src="{{book.cover.url}}" class="rounded-start" alt="..." height="250px" width="170px">
    </div>
    <div class="col-md-8 lh-lg ps-5">
      <div class="card-body mt-3">
        <h5 class="card-title"><strong>TITLE :</strong>{{book.title}}</h5>
        <p class="card-text"><strong>AUTHOR :</strong> {{book.author}}</p>
        <p class="card-text"><strong>LANGUAGE :</strong> {{book.language}}</p>
        <p class="card-text"><strong>PRICE :</strong>{{book.price}}</p>
          <a href="{{book.pdf.url}}" type="button" class="btn btn-danger">DOWNLOAD</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

librarys1/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3"><b>Edit Book Details</b></h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3">
  <label  class="form-label">Title</label>
  <input type="text" class="form-control" name="t" value="{{book.title}}">
</div>

        <div class="mb-3">
  <label  class="form-label">Author</label>
  <input type="text" class="form-control" name="a" value="{{book.author}}">
</div>

            <div class="mb-3">
  <label  class="form-label">Price</label>
  <input type="text" class="form-control" name="p" value="{{book.price}}" >
</div>

<div class="mb-3">
  <label  class="form-label">pages</label>
  <input type="text" class="form-control" name="pa" value="{{book.pages}}">
</div>


<div class="mb-3">
  <label  class="form-label">language</label>
  <input type="text" class="form-control" name="l" value="{{book.language}}">
</div>


<div class="mb-3">
  <label  class="form-label">Cover</label>
    <img src="{{book.cover.url}}" height="100px" width="75px">
  <input type="file" class="form-control" name="i">
</div>



<div class="mb-3">
  <label  class="form-label">Pdf</label>
    <a href="{{book.pdf.url}}">{{book.pdf}}</a>
  <input type="file" class="form-control" name="f">
</div>


    <div class="mb-3">
        <input type="submit" value="ADD">
    </div>




</form>
{% endblock %}

librarys1/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center mt-3 text-info"><B>Welcome to Home page</b></h1>

{% endblock %}

librarys1/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3"><b>Login Page</b></h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3">
  <label  class="form-label">User name</label>
  <input type="text" class="form-control" name="u"  placeholder="enter user name">
</div>

        <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>



    <div class="mb-3">
        <input type="submit" class="form-control btn btn-primary">
    </div>




</form>
{% endblock %}

librarys1/templates/logout.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2><b>logout page</b></h2>
{% endblock %}

librarys1/templates/userregister.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3"><b>User Register Form</b></h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

<div class="mb-3">
  <label  class="form-label">User name</label>
  <input type="text" class="form-control" name="u"  placeholder="enter user name">
</div>


<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>


<div class="mb-3">
  <label  class="form-label">confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter confirm password">
</div>


<div class="mb-3">
  <label  class="form-label">First Name</label>
  <input type="text" class="form-control" name="f"  placeholder="enter first name">
</div>


<div class="mb-3">
  <label  class="form-label">Last Name</label>
  <input type="text" class="form-control" name="l" placeholder="enter last name">
</div>


<div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="email" class="form-control" name="e"  placeholder="enter email">
</div>


<div class="mb-3">
  <label  class="form-label">Phone</label>
  <input type="number" class="form-control" name="ph"  placeholder="enter phone number">
</div>


<div class="mb-3">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control" name="a"  placeholder="enter address">
</div>



<div class="mb-3">
    <input type="submit" class="form-control btn btn-primary">
</div>




</form>



{% endblock %}

librarys1/templates/view.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center mt-3"><b>View Books</b></h2>

<table class="table table-bordered border border-5 border-primary bg-success text-light">
    <tr>
        <th>COVER</th><th>TITLE</th><th>AUTHOR</th><th>PRICE</th><th>PAGES</th><th>LANGUAGES</th><th>PDF</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>


{% for i in book %}

<tr>
    <td><img src="{{i.cover.url}}" height="100px" width="100px"></td>
    <td>{{i.title}}</td>
    <td>{{i.author}}</td>
    <td>{{i.price}}</td>
    <td>{{i.pages}}</td>
    <td>{{i.language}}</td>

    <td><a href="{{i.pdf.url}}" class="btn btn-danger">DOWNLOAD</a></td>
    <td><a href="{% url 'books:detail' i.id %}" class="btn btn-danger">view</a></td>
    <td><a href="{% url 'books:edit' i.id %}" class="btn btn-danger">edit</a></td>
    <td><a href="{% url 'books:delete' i.id %}" class="btn btn-danger">delete</a></td>

</tr>

{% endfor %}

</table>

<!--<ol>-->
<!--    {% for i in book %}-->
<!--    <li>Book Details</li>-->
<!--    <ul>-->
<!--        <li>Title:{{i.title}}</li>-->
<!--        <li>:Author{{i.author}}</li>-->
<!--        <li>Price:{{i.price}}</li>-->

<!--    </ul>-->
<!--{% endfor %}-->



{% endblock %}